### ISSUE TITLE
[Feature request] Code Profiling for Ruby/Rails

### ISSUE THREAD

**Issue by gcarrion-gfrmedia** [appoptics/appoptics-apm-ruby#108]
We're looking for alternatives for our current APM service and noticed that AppOptics doesn't yet support for Code Profiling for Ruby/Rails.

Any plans to add this feature to the AppOptics Ruby Agent?

**Comment by prettycoder** [comment]
:) working on it, see branch https://github.com/appoptics/appoptics-apm-ruby/tree/AO-12790_profiling
The solution is written in c++ and uses the same approach as stackprof. 
Still a lot of details to work out.

**Comment by prettycoder** [comment]
FYI: 
Prerelease version is available from packagecloud:

Add this to the end of the Gemfile
```
source "https://packagecloud.io/solarwinds/appoptics-apm-ruby" do
  gem 'appoptics_apm' , '4.13.0.pre1'
end
```

more prereleases coming...

Please report any bugs, anomalies, ideas, feature requests...

**Comment by prettycoder** [comment]
make sure to add 
`AppOpticsAPM::Config[:profiling] = :disabled` in the config file
The sampling interval can be changed to as little as 1ms
`AppOpticsAPM::Config[:profiling_interval] = 1`

The profiler is modeled after stackprof
The profile shows up when looking at a trace. If it is deemed the most interesting info about the trace it will show in the summary view and otherwise you have to dig into a span in the details view

**Comment by prettycoder** [comment]
Finally released today!
https://rubygems.org/gems/appoptics_apm
